  auth:
    rest: "8081"
    grpc: "9091"
    mysql:
      host: "127.0.0.1"
      port: "3307"
      user: "root"
      password: "123456"
      database: "auth"
    jwt:
      secret: "emergency-system-secret-2026"
      expiry_hours: 24
    
  stock:
    rest: "8082"
    grpc: "9092"
    host: "127.0.0.1"
    mysql:
      host: "127.0.0.1"
      # host: "mysql"
      port: "3307"
      user: "root"
      password: "123456"
      database: "stock"
    
  dispatch:
    rest: "8083"
    grpc: "9093"
    host: "127.0.0.1"
    mysql:
      host: "127.0.0.1"
      # host: "mysql"
      port: "3307"
      user: "root"
      password: "123456"
      database: "dispatch"

  statistics:
    rest: "8084"
    grpc: ""
    mysql:
      host: "localhost"
      port: "3306"
      user: "root"
      password: "123456"
      database: "statistics"

  # logistics service only has REST API
  logistics:
    rest: "8085"
    grpc: "9095" # Added grpc port for logistics
    host: "127.0.0.1"
    mysql:
      host: "127.0.0.1"
      port: "3307"
      user: "root"
      password: "123456"
      database: "logistics"

security:
  encryption_key: "emergency-system-aes-key-32chars"

gaode_maps:
  api_key: "bff42bf37382382b61e29c13b4964ad4"
  base_url: "https://restapi.amap.com"

