services:
  # Auth Service (认证服务)
  auth:
    build:
      context: ../internal/auth
      dockerfile: dockerfile
    container_name: auth
    ports:
      - "8081:8081" # REST API
      - "9091:9091" # gRPC
    networks:
      - emergency
    restart: unless-stopped
    volumes:
      - ../internal/common/config:/root/emergency-material-system/backend/internal/common/config

  # Stock Service (物资库存服务)
  stock:
    build:
      context: ../internal/stock
      dockerfile: dockerfile
    container_name: stock
    ports:
      - "8082:8082" # REST API
      - "9092:9092" # gRPC
    networks:
      - emergency
    restart: unless-stopped
    volumes:
      - ../internal/common/config:/root/emergency-material-system/backend/internal/common/config

  # Dispatch Service (调度服务)
  dispatch:
    build:
      context: ../internal/dispatch
      dockerfile: dockerfile
    container_name: dispatch
    ports:
      - "8083:8083" # REST API
      - "9093:9093" # gRPC
    networks:
      - emergency
    restart: unless-stopped
    volumes:
      - ../internal/common/config:/root/emergency-material-system/backend/internal/common/config

  # Statistics Service (统计服务)
  statistics:
    build:
      context: ../internal/statistics
      dockerfile: dockerfile
    container_name: statistics
    ports:
      - "8084:8084" # REST API
    networks:
      - emergency
    restart: unless-stopped
    volumes:
      - ../internal/common/config:/root/emergency-material-system/backend/internal/common/config

  # Logistics Service (物流服务)
  logistics:
    build:
      context: ../internal/logistics
      dockerfile: dockerfile
    container_name: logistics
    ports:
      - "8085:8085" # REST API
    networks:
      - emergency
    restart: unless-stopped
    volumes:
      - ../internal/common/config:/root/emergency-material-system/backend/internal/common/config

  # mysql database
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    networks:
      - emergency
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=stock
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  emergency:
    driver: bridge
