services:
  # Auth Service (认证服务)
  auth:
    build:
      context: ../internal/auth
      dockerfile: dockerfile
    container_name: auth
    ports:
      - "8081:8081" # REST API
      - "9091:9091" # gRPC
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ../internal/common/config:/root/emergency-material-system/backend/internal/common/config

  # Stock Service (物资库存服务)
  stock:
    build:
      context: ../internal/stock
      dockerfile: dockerfile
    container_name: stock
    ports:
      - "8082:8082" # REST API
      - "9092:9092" # gRPC
    restart: unless-stopped
    volumes:
      - ../internal/common/config:/root/emergency-material-system/backend/internal/common/config

  # Dispatch Service (调度服务)
  dispatch:
    build:
      context: ../internal/dispatch
      dockerfile: dockerfile
    container_name: dispatch
    ports:
      - "8083:8083" # REST API
      - "9093:9093" # gRPC
    restart: unless-stopped
    volumes:
      - ../internal/common/config:/root/emergency-material-system/backend/internal/common/config

  # Statistics Service (统计服务)
  statistics:
    build:
      context: ../internal/statistics
      dockerfile: dockerfile
    container_name: statistics
    ports:
      - "8084:8084" # REST API
    restart: unless-stopped
    volumes:
      - ../internal/common/config:/root/emergency-material-system/backend/internal/common/config

  # Logistics Service (物流服务)
  logistics:
    build:
      context: ../internal/logistics
      dockerfile: dockerfile
    container_name: logistics
    ports:
      - "8085:8085" # REST API
    restart: unless-stopped
    volumes:
      - ../internal/common/config:/root/emergency-material-system/backend/internal/common/config

  # mysql database
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./data/mysql:/var/lib/mysql

  # influxdb
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    restart: unless-stopped
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
